[tox]
envlist = marshmallow3, marshmallow4

[testenv]
pip_pre = false
deps =
    pytest<9
    pytest-cache<2
    pytest-cov<7
    WebTest<4
    colander<3

[testenv:marshmallow3]
deps =
    {[testenv]deps}
    marshmallow>=3.13,<4
commands =
    pytest tests/ {posargs:-v}

[testenv:marshmallow4]
deps =
    {[testenv]deps}
    marshmallow>=4
commands =
    pytest tests/ {posargs:-v}
