name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6

      - name: Run linting and formatting checks
        run: make lint

  unit-tests:
    name: Unit Tests
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        marshmallow-version: ["marshmallow>=3.13,<4", "marshmallow>=4"]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: make install

      - name: Install marshmallow ${{ matrix.marshmallow-version }}
        run: .venv/bin/pip install "${{ matrix.marshmallow-version }}"

      - name: Run unit tests
        run: make test

      - name: Write LCOV report
        if: github.event_name == 'push' && matrix.python-version == '3.14'
        run: .venv/bin/coverage lcov -o coverage.lcov

      - name: Coveralls
        if: github.event_name == 'push' && matrix.python-version == '3.14'
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: coverage.lcov

  docs:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6

      - name: Build docs
        run: make docs
